management:
  influx:
    metrics:
      export:
        bucket: asdf
        token: hXPU0j1t3PbMaDSDEElC-jv9bb8NPl1j2ErddM1eGlsAhtWJp8uXNxyR15qW-YDbK1e2FLu5lF1HOLx6dxhimA==
        org: asdf

logging:
  level:
    # Will generate a log everytime a publish event occurs, about once a minute. Change to Info to remove log. 
    io.micrometer.influx.InfluxMeterRegistry : DEBUG 

spring: 
  datasource: 
    url:  jdbc:postgresql://172.23.121.7:5432/mydb
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect